Update Dockerfile
Added authentikProxyAuth to download

diff --git a/mantis/Dockerfile b/mantis/Dockerfile
--- a/mantis/Dockerfile
+++ b/mantis/Dockerfile
@@ -7,7 +7,8 @@ LABEL maintainer="wrccdc"
 
 ENV MANTIS_VER=2.27.1
 ENV MANTIS_URL=https://sourceforge.net/projects/mantisbt/files/mantis-stable/${MANTIS_VER}/mantisbt-${MANTIS_VER}.tar.gz
-ENV OIDC_PLUGIN_URL=https://github.com/initOS/MantisOIDC/archive/refs/heads/scopes-and-user-mapping.tar.gz
+#ENV OIDC_PLUGIN_URL=https://github.com/initOS/MantisOIDC/archive/refs/heads/scopes-and-user-mapping.tar.gz
+ENV AUTHENTIK_AUTH_PLUGIN_URL=https://github.com/giga1699/authentikProxyAuth/archive/refs/heads/master.zip
 
 # Install dependencies and Composer
 RUN set -eux; \
@@ -24,23 +25,28 @@ RUN set -eux; \
 RUN a2enmod rewrite
 
 ENV MANTIS_FILE=mantisbt.tar.gz
-ENV OIDC_PLUGIN_FILE=MantisOIDC.tar.gz
+#ENV OIDC_PLUGIN_FILE=MantisOIDC.tar.gz
+ENV AUTHENTIK_PLUGIN_FILE=authentikLogin.tar.gz
 
 WORKDIR /var/www/html
 
 RUN set -eux; \
     curl -fSL "${MANTIS_URL}" -o "${MANTIS_FILE}"; \
-    curl -fsSL "${OIDC_PLUGIN_URL}" -o "${OIDC_PLUGIN_FILE}"; \
+    #curl -fsSL "${OIDC_PLUGIN_URL}" -o "${OIDC_PLUGIN_FILE}"; \
+    curl -fsSL "${AUTHENTIK_AUTH_PLUGIN_URL}" -o "${AUTHENTIK_PLUGIN_FILE}"; \
     tar -xzf "${MANTIS_FILE}" --strip-components=1; \
-    mkdir -p ./plugins/MantisOIDC; \
-    tar -xzf "${OIDC_PLUGIN_FILE}" -C ./plugins/MantisOIDC --strip-components=1; \
-    rm "${MANTIS_FILE}" "${OIDC_PLUGIN_FILE}"; \
+    #mkdir -p ./plugins/MantisOIDC; \
+    #tar -xzf "${OIDC_PLUGIN_FILE}" -C ./plugins/MantisOIDC --strip-components=1; \
+    #rm "${MANTIS_FILE}" "${OIDC_PLUGIN_FILE}"; \
+    mkdir -p ./plugins/authentikProxyAuth; \
+    tar -xzf "${AUTHENTIK_PLUGIN_FILE}" -C ./plugins/authentikProxyAuth --strip-components=1; \
+    rm "${MANTIS_FILE}" "${AUTHENTIK_PLUGIN_FILE}"; \
     chown -R www-data:www-data .; \
     mv /var/www/html/admin /var/www/; \
     ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime; \
-    echo 'date.timezone = "America/Los_Angeles"' > /usr/local/etc/php/conf.d/timezone.ini; \
-    cd plugins/MantisOIDC/pages/assets/lib/OpenID-Connect-PHP; \
-    composer install || echo "composer failed"
+    echo 'date.timezone = "America/Los_Angeles"' > /usr/local/etc/php/conf.d/timezone.ini;
+    #cd plugins/MantisOIDC/pages/assets/lib/OpenID-Connect-PHP; \
+    #composer install || echo "composer failed"
 
 COPY wrccdc.png /var/www/html/images/logo.png
 RUN cp /var/www/html/images/logo.png /var/www/html/images/mantis_logo.png \
